export {default as JavascriptImage } from '../images/javascript-logo.png'
export {default as GitImage } from '../images/git-logo.png'
export { default as PythonImage } from '../images/python-svgrepo-com.png'
export { default as JavaImage } from '../images/java-svgrepo-com.png'
export { default as NextImage } from '../images/next-js-svgrepo-com.png'
export { default as TailwindImage } from '../images/tailwind-logo.png'
export { default as CSharpImage } from '../images/c-sharp-svgrepo-com.png'
export { default as PrismaImage } from '../images/light-prisma-svgrepo-com.png'
export { default as DockerImage } from '../images/docker-logo.png'
export { default as MongoImage } from '../images/mongo-logo.png'
export { default as NodeImage } from '../images/node-logo.png'
export { default as ReactImage } from '../images/react-logo.png'
export { default as ProfileImage } from '../images/travis-opened-svgrepo-com.png'
export { default as LogoImage } from '../images/code-tech-dev-svgrepo-com.png'
export { default as Facebook } from '../images/facebook.png'
export { default as Instagram } from '../images/instagram.png'
export { default as LinkedIn } from '../images/linkedin.png'